### ISSUE TITLE
bug: fail to produce block in debug mode

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1183]
## Description

in `crates/client/block-proposer/src/lib.rs`
in `propose_with`
l320:
```rust
        let (block, storage_changes, proof) = block_builder.build()?.into_inner();
```
in `substrate//client/block-builder/src/lib.rs`
l249:
```rust
		debug_assert_eq!(
			header.extrinsics_root().clone(),
			HashFor::<Block>::ordered_trie_root(
				self.extrinsics.iter().map(Encode::encode).collect(),
				sp_runtime::StateVersion::V0,
			),
		);
```

This assert is only run in debug mode. And it fails for the block where a new contract has been declared.

## Guess
I guess it may be due to how `ContractClass` are encoded. But I may be wrong.

## How to reproduce?
Run the starknet-rpc-test on `./taget/debug/madara` rather than `./target/release/madara`

**Comment by kalaninja** [comment]
Hey @tdelabro, I'd like to investigate this one.

**Comment by tdelabro** [comment]
Thanks, @kalaninja, It's strange I'm not sure the behaviour is still there on the current main.
Tell us what you find.

**Comment by kalaninja** [comment]
Yes, the behaviour is still here. The weird thing is that it fails for native runtime only. It's fine with wasm.

**Comment by tdelabro** [comment]
That's not that weird. We probably have different encoding/decoding scheme base on std/no_std

**Comment by kalaninja** [comment]
Yes, should be something with std feature toggle for sure.

**Comment by tdelabro** [comment]
@kalaninja any update?

**Comment by kalaninja** [comment]
@tdelabro cannot reproduce with the latest commit

**Comment by tdelabro** [comment]
@kalaninja Is it because they removed the assert_debug! entirely? Or because this assert_debug is not triggered anymore?

**Comment by tdelabro** [comment]
https://github.com/paritytech/polkadot-sdk/blob/polkadot-v1.3.0/substrate/client/block-builder/src/lib.rs#L231

It looks like the assert is still there.
Did you run in debug mode and created declare transaction?

If so we will close the issue :)

**Comment by kalaninja** [comment]
yep. somehow it was fixed [here](https://github.com/keep-starknet-strange/madara/pull/1264) during the polkadot-sdk update

**Comment by edisontim** [comment]
Hey! If I run with 
```cargo run -- --dev --sealing=manual```
 it's crashing with this error when I generate a block: 
```2023-11-24 17:16:55 Accepting new connection 1/100
2023-11-24 17:16:56 failed to validate tx: Transaction validation has failed.
2023-11-24 17:16:56 Failed to submit extrinsic: Pool(InvalidTransaction(InvalidTransaction::BadProof))
2023-11-24 17:16:56 Accepting new connection 2/100
2023-11-24 17:16:56 Accepting new connection 1/100
2023-11-24 17:16:56 Accepting new connection 2/100
2023-11-24 17:16:56 🙌 Starting consensus session on top of parent 0xb19202a3ecd8cc35a8bd655cc5f8a5fb2b8d4e6b6166ebf7e541ffc7260531fe
libunwind: stepWithCompactEncoding - invalid compact unwind encoding
[1]    94914 abort      cargo run -- --dev --sealing=manual```
but if I run from the binary: 
```/target/release/madara --dev --sealing=manual```
I don't have anything. @apoorvsadana was wondering if it wasn't related

**Comment by apoorvsadana** [comment]
I remember the declare issue before and it used to fail with a different error message, maybe the message has changed after the rebase with Polkadot but it looks like this error still exists. @tdelabro @kalaninja can you confirm? We can reopen this issue in that case

**Comment by tdelabro** [comment]
@edisontim I pulled the main on my machine and ran the RPC tests it passed. It also passes in the CI.
Did you change nothing and it failed or is it when you create a declareTx that it fails?
